spring.application.name=examenlpseg
server.port=9191

spring.datasource.url=jdbc:oracle:thin:@//localhost:1522/FREEPDB1
spring.datasource.username=biblioteca
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false
